catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('blog/blogs/', views.BlogListView.as_view(), name = 'blogs'),
    path('blog/<int:pk>', views.BlogDetailView.as_view(), name = 'blog-detail'),
    path('blog/<int:pk>/update', views.BlogUpdate.as_view(), name = 'blog-update'),
     path('blog/<int:pk>/del', views.DeleteBlog.as_view(), name = 'delete-post')
]

urlpatterns += [
    path('blog/bloggers', views.BloggerListView.as_view(), name = 'bloggers'),
    path('blog/blogger/<int:pk>', views.BloggerDetailView.as_view(), name = 'blogger-detail'),
    path('blog/bloggerme/<int:pk>/', views.view_profile, name = 'profile-detail'),
    path('blog/bloggerme/<int:pk>/edit', views.edit_profile, name = 'edit-profile')
]
 
urlpatterns += [
    
    path('blog/<int:pk>/create/', views.comment_create, name = 'add-comment'),
    path('blog/bloggerme/<int:pk>/newpost/', views.new_post, name = 'new-post')
]

urlpatterns += [
    path('blog/register/', views.register, name = 'register')
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
]

urlpatterns += [
    path('catalog/', include('catalog.urls'))
    
]

urlpatterns += [
    path('', RedirectView.as_view(url = 'catalog', permanent = True))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls'))
]

catalog/models.py
from django.db import models
from django.urls import reverse

from datetime import date
from django.urls import reverse #Used to generate URLs by reversing the URL patterns
from django.contrib.auth.models import User #Blog author or commenter
from django.db.models.signals import post_save
from django.dispatch import receiver


   

class Blogger(models.Model):
    user = models.OneToOneField(User, primary_key=True, on_delete = models.CASCADE)
    first_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)
    email = models.EmailField(max_length=150, default=False)
    bio = models.TextField(max_length = 500, help_text = "Enter your bio here.")

    class Meta:
        ordering = [ 'user','bio']

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('blogger-detail', kwargs={
            'pk': self.pk
        })
    def get_full_name(self):
        return self.user.first_name + ' ' + self.user.last_name

    @receiver(post_save, sender=User)
    def update_blogger_signal(sender, instance, created, **kwargs):
        if created:
            Blogger.objects.create(user=instance)
        instance.blogger.save()

        



class Blog(models.Model):
    title = models.CharField(max_length = 200)
    post_date = models.DateField( default = date.today)
    author = models.ForeignKey(Blogger, on_delete = models.SET_NULL, null = True)
    description = models.TextField(max_length = 2000, help_text = "Enter your text here.")
    
    class Meta:
        ordering = ["-post_date"]

    def  __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog-detail', args=[str(self.id)])


class Comment(models.Model):
    
    author = models.ForeignKey(User,  on_delete = models.SET_NULL, null=True, default = False)
    body = models.TextField(max_length = 160, null = False, blank = False)
    post_date = models.DateTimeField(auto_now_add = True)
    post = models.ForeignKey(Blog,  on_delete = models.CASCADE, related_name = 'comments', null = True)

    class Meta:
        ordering = ["-post_date"]

    def __str__(self):
        return self.body
   
    
        

catalog/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Comment, Blogger, Blog
from django.contrib.auth.forms import UserChangeForm, UserCreationForm


class CommentForm(forms.ModelForm):
    
    class Meta:
            model = Comment
            
            fields = ['body',]

class EditBloggerForm(forms.ModelForm):
    class Meta:
        model = Blogger
        fields = (
            'bio',
        )

class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username','first_name', 'last_name', 'email')

class SelfBlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'description')

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, help_text='Last Name')
    last_name = forms.CharField(max_length=100, help_text='Last Name')
    email = forms.EmailField(max_length=150, help_text='Email')
    
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)

catalog/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect
from .models import Comment, Blogger, Blog
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin    
from .forms import CommentForm, EditBloggerForm, EditUserForm, SelfBlogForm, SignUpForm
from django.urls import reverse_lazy, reverse
from django.contrib.auth import login, authenticate
# Create your views here.

def index(request):
    blogger_count = Blogger.objects.all().count()
    blog_count = Blog.objects.all().count()
    comment_count = Comment.objects.all().count()

    context = {'blogger_count':blogger_count,
                'blog_count': blog_count,
                'comment_count': comment_count
                }
    return render(request, 'index.html', context = context)

  

def register(request):
    form = SignUpForm(request.POST)
    if form.is_valid():
        user = form.save()
        user.refresh_from_db()
        user.blogger.first_name = form.cleaned_data.get('first_name')
        user.blogger.last_name = form.cleaned_data.get('last_name')
        user.blogger.email = form.cleaned_data.get('email')
        user.save()
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect('index')
    else:
        form = SignUpForm()
    return render(request, 'registration/register_form.html', {'form': form})


class BlogListView( generic.ListView):
    model = Blog
    

class BlogDetailView( generic.DetailView):
    model = Blog
    

class BlogUpdate(UpdateView):
    model = Blog
    fields = ('title', 'description')

class DeleteBlog(DeleteView):
    model = Blog
    success_url = reverse_lazy('index')

class BloggerListView( generic.ListView):
    model = Blogger
    

class BloggerDetailView( generic.DetailView):
    model = Blogger

@login_required
def comment_create(request, pk):
    post = get_object_or_404(Blog, pk=pk)
    user_ = Blogger.objects.get(user = request.user)
    if request.method == "POST":
        
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit = False)
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect('blog-detail', pk=post.pk)
    else:
        form = CommentForm()
        context = {
            'form': form,
            'post': post,
            'user': request.user.username
        }
        return render(request, 'catalog/create_comment.html', context )


@login_required
def view_profile(request,pk):
    user= get_object_or_404(User, pk = pk)
    blogger = user.blogger
      
    args = {'user': user,
             'blogger': blogger,
            }
    return render(request, 'catalog/profile_detail.html', args)


@login_required
def edit_profile(request, pk):
   
    if request.method == 'POST':
        user_form = EditUserForm(request.POST, instance = request.user)
        blogger_form = EditBloggerForm(request.POST, instance = request.user.blogger)

        if user_form.is_valid and blogger_form.is_valid():
            user_form.save()
            blogger_form.save()
        return redirect('profile-detail', pk = request.user.id)
    else:
        user_form = EditUserForm(instance = request.user)
        blogger_form = EditBloggerForm(instance = request.user.blogger)
        context = {
            'user_form': user_form,
            'blogger_form': blogger_form

        }
        return render(request, 'catalog/edit_profile.html', context)


def new_post(request, pk):
        
    if request.method == 'POST':
        user_ = Blogger.objects.get(user = request.user)
        form = SelfBlogForm(request.POST)
        if form.is_valid():
            blog = form.save(commit = False)
            blog.author = user_
            blog.save()
            return redirect('profile-detail', pk=request.user.id)
    else:
        form = SelfBlogForm()
        return render(request, 'catalog/new_post.html', {'form': form})

catalog/templates/catalog/blog_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Delete Post</h1>
  <p>Do you want to delete:  <strong>{{ blog.title }}</strong>?</p>

  <form action="" method="POST">
    {% csrf_token %}
    <a class = "btn" href="{% url 'profile-detail' blog.author.pk %}">Cancel</a> 
    <input type="submit" value="Yes, delete">
      
</form>

{% endblock %}

catalog/templates/catalog/blog_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h3>{{ blog.title}}</h3>
<p><strong>Post Date: </strong>{{ blog.post_date}}</p>
<p><strong>Author:</strong><a href="{% url 'blogger-detail' blog.author.pk %}">{{ blog.author.get_full_name }}</a></p>
<p><strong>Description:</strong></p>
<p>{{blog.description}}</p>
<hr/>
<p><strong>Comments</strong></p>
<p>{{blog.comment}}</p>

{% if request.user.is_authenticated %}
<p><a href="{% url 'add-comment' blog.pk %}">Add comment</a></p>
{% else %}
<p><a href="{% url 'login'%}?next={{request.path}}">Login </a> to add a new comment</p>
{% endif %}
<hr>

{% for comment in blog.comments.all %}
    <blockquote>
        <p style="line-height: 0.50;"><strong>{{ comment.body}}</strong></p>
        <footer style="line-height: 0.50;"><i> by {{ comment.author }} | {{ comment.post_date |timesince }} ago</i></footer>
    </blockquote>
    <hr/>
{% empty %}
    <p>No comments here yet :(</p>
{% endfor %}

{%endblock%}

catalog/templates/catalog/blog_form.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h1>Edit Post</h1>

<form method="POST">
    {% csrf_token %}
    {{form | crispy}}
   
    <a href="{% url 'profile-detail' user.id %}">Cancel</a>
    
    <input type="submit" value="Save changes">

</form>

{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Blog List</h1>
<hr/>


  {% if blog_list %}
  <table style="width: 100%;">
    <tr>
      <th>Title</th>
      <th>Post Date</th>
      <th>Author</th>
    </tr>

    {% for blog in blog_list %}
    <tr>
      <td><a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a></td> 
      <td>{{blog.post_date}}</td>
      <td><a href="{% url 'blogger-detail' blog.author.pk %}"> {{blog.author}}</a></td> 
                     
    </tr>
    {% endfor %}
  </table>
  {% else %}
    <p>There are no blogs.</p>
  {% endif %}  
 
{% endblock %}

catalog/templates/catalog/blogger_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h3>Blogger: {{ blogger }}</h3> 
<hr>
<h5>Bio</h5>
<p>{{ blogger.bio }}</p>


<div>
    <p><strong>Posts</strong></p>
    <ul>
        {% for blog in blogger.blog_set.all %}
        <li><a href="{% url 'blog-detail' blog.pk %}">{{ blog }}</a> ({{ blog.post_date }})</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

catalog/templates/catalog/blogger_form.html
{% extends "base_generic.html" %}

{% block content %}
<h3>{{blogger}} edit</h3>
<hr/>
    <form action="" method="POST">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>

{% endblock %}

catalog/templates/catalog/blogger_list.html
{% extends "base_generic.html" %}

{% block content %}

{% if blogger_list%}
<h1>Bloggers</h1> 
<hr/>
{% for blogger in blogger_list%}
<ul>
    <li style="line-height: 0.50;"><a href="{{ blogger.get_absolute_url }}">{{ blogger }}</a></li>
</ul>
{% endfor %}
{% else %}
<p>There is no blogger!</p>
{% endif %}
{% endblock %}

catalog/templates/catalog/create_comment.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}

{% block content %}

<p>Post your comment for: <a href="{% url 'blog-detail' post.pk %}">{{ post.title }}</a></p>
<form method="POST">
    {% csrf_token %}
    {{ form.body }}
    <p><a href="{% url 'blog-detail' post.pk %}">Cancel</a>   <input type="submit" value="Save">  </p>

</form>

{% endblock %}

catalog/templates/catalog/edit_profile.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h1>My profile</h1>

<form method="POST">
    {% csrf_token %}
    {{user_form | crispy}}
    {{blogger_form|crispy}}
    <a href="{% url 'profile-detail' user.id %}">Cancel</a>
    
    <input type="submit" value="Save changes">

</form>

{% endblock %}

catalog/templates/catalog/new_post.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{form |crispy }}
    
    
    <input type="submit" value="Save" style="padding: 5px 30px; " >
</form>
{% endblock %}

catalog/templates/catalog/profile_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1><i>My Blog:</i> {{user.username}}</h1><h3 align = 'right'><a href="{% url 'edit-profile' user.id %}" >Edit</a></h3>

<p><i>First-name: </i> <strong> {{ user.first_name }}</strong></p>
<p><i>Last-name: </i><strong>  {{user.last_name}}</strong></p>
<p><i>E-mail: </i><strong>  {{user.email}}</strong></p>
{{ blogger.bio }}

<hr/>
<div>
    <p><strong>My Posts</strong></p>
    <table>
    
        {% for blog in blogger.blog_set.all %}
        <tr>
        <td><a href="{% url 'blog-detail' blog.pk %}">{{ blog }}</a> </td>
        <td>   ({{ blog.post_date }})</td> 
        <td><a href="{% url 'blog-update' blog.pk %}">Edit</a></td>
        <td><a href="{% url 'delete-post' blog.pk %}">Delete</a></td>
        </tr>
        {% endfor %}
    
    </table>
    <p><a href="{% url 'new-post' blogger.pk %}">Add new post</a></p>
</div>

{% endblock %}